README.md
Fixed a minor typo
As a first pull request, I hope it's not more cumbersome than not.
By the way, great utility ^^
=> Fixed a typo line 304 (spces -> spaces)

CHANGES.md, README.md
forgot to push these up before I made the release.
=> readme tweaks:

addons/gut/test.gd, gut_tests_and_examples/test/unit/test_test.gd
String assertion suggestions from #24.
=> String assertions

addons/gut/test.gd, gut_tests_and_examples/test/unit/test_test.gd
Implementation of assert_has_method from #3.
=> Has method assertion

addons/gut/gut_cmdln.gd, templates/.gutconfig.json
=> Added opacity option to command line/config file

addons/gut/test.gd, test/samples/test_readme_examples.gd, test/unit/test_gut.gd, test/unit/test_test.gd
This is my suggested implementation for https://github.com/bitwes/Gut/issues/64, so we have an example to discuss.
I think it would primarily be useful for comparing floats, and things that contain floats (like Vectors).
=> Assert Almost Equals

.gutconfig.json, addons/gut/gut.gd, addons/gut/gut_cmdln.gd, addons/gut/gut_gui.gd, scenes/main.tscn, templates/.gutconfig.json
Reverts bitwes/Gut#71, this should have gone into next_release.
=> Revert "Add maximize option to command line and the editor"

.gutconfig.json, addons/gut/gut.gd, addons/gut/gut_cmdln.gd, addons/gut/gut_gui.gd, scenes/main.tscn, templates/.gutconfig.json
Now I can't figure out how to get the last PR back so now I'm just gonna merge it into master.
=> Revert "Revert "Add maximize option to command line and the editor""

CHANGES.md, addons/gut/doubler.gd, addons/gut/gut.gd, addons/gut/method_maker.gd, addons/gut/optparse.gd, addons/gut/stubber.gd, addons/gut/test.gd, addons/gut/utils.gd, test/samples/test_readme_examples.gd, test/unit/test_gut.gd, test/unit/test_gut_directory.gd, test/unit/test_test.gd
This fixed typos found using [codespell](https://github.com/codespell-project/codespell) :smiley:
=> Fix several typos

addons/gut/optparse.gd
=> Remove script option only if present while parsing command line options

addons/gut/test.gd, test/unit/test_test.gd
- Fixed the _is_connected function to check for connections between two objects
- Added more unit tests for assert_connected as well as assert_not_connected
Thank you again for being so patient about this :)
Please review the changes
=> Fix connection asserts

.gutconfig.json, CHANGES.md, addons/gut/gut.gd, addons/gut/test.gd, test/unit/test_doubler.gd, test/unit/test_gut.gd, test/unit/test_gut_yielding.gd, test/unit/test_strutils.gd
Refactor GUT so that there is now a function that runs a single test.  This fixes issues where some things were not being done per parameterized test execution.  Fixes #196, Fixes #197, Fixes #202.
=> Refactor running tests

addons/gut/test.gd, test/samples/test_readme_examples.gd, test/unit/test_test.gd
This PR is fixing the issue #66 , which is to add an "assert_not_between" test condition.
As discussed in the issue, this condition should probably be exclusive, which is how I implemented in this PR.
=> Issue #66 - Implemented assert_not_between

.gutconfig.json, CHANGES.md, addons/gut/array_diff.gd, addons/gut/gut.gd, addons/gut/strutils.gd, addons/gut/test.gd, readme_gutconfig.json, test/samples/test_readme_examples.gd, test/unit/test_array_diff.gd, test/unit/test_strutils.gd, test/unit/test_test.gd
* Adds better array difference display.
* Changed printing of floats to always have one point of precision.
* Changed printing of strings to always be enclosed with double quotes.
* Used new features to  show differences in parameters better.
=> Issue 152, resolves #152

.gitattributes
All files apart from `/addons` should be removed from ZIP download.
`icon.png.import`
`readme_gutconfig.json`
All lines got spaces for layout
=> Remove more files from ZIP download

addons/gut/gut.gd
=> Updates comment in gut.gd to link to readme and wiki

addons/gut/doubler.gd, addons/gut/gut.gd, addons/gut/utils.gd
nothing seems to fail but I didn't tested it very much either ;)
#273
=> Rework utils

CHANGES.md, addons/gut/gut.gd, addons/gut/input_factory.gd, addons/gut/input_sender.gd, addons/gut/test.gd, addons/gut/utils.gd, test/gut_test.gd, test/unit/test_gut_yielding.gd, test/unit/test_input_factory.gd, test/unit/test_input_sender.gd, test/unit/test_test.gd
Introduces classes:
* InputFactory
* InputSender
=> Add ability to mock input

addons/gut/test.gd
=> Update documentation for assert_is/assert_extends

addons/gut/gui/GutBottomPanel.gd
=> Typo "conrfiguration"

CHANGES.md, addons/gut/gut.gd, addons/gut/gut_config.gd
Only parse scripts that match the selected script name.
=> I364 Speed up launch when selected script specified.

addons/gut/gui/gut_config_gui.gd
fix #443 
Hello, please review me :) !
=> [fix] issue #443 ParseError in gut_config_gui

.gut_editor_shortcuts.cfg, addons/gut/gui/BottomPanelShortcuts.tscn, addons/gut/gui/ShortcutButton.gd, scenes/TestShortcuts.tscn
Got the shortcuts dialog showing and owrking
=> shortcuts working

CHANGES.md, addons/gut/gui/gut_config_gui.gd
=> output_font_name and output_font_size are now saved correctly

CHANGES.md, addons/gut/gut_config.gd, addons/gut/utils.gd, test/unit/test_utils.gd
The panel was not setting the double strategy correctly.  It had the wrong default and was not converting the float value correctly.
=> Panel double strat

test/unit/test_bugs/test_i608_mouse_motion_buttons.gd
#613 Implemented the the issue, but  @TGRCdev had graciously provided some tests to illustrate the issue.  This PR adds those tests juuuuuust to be sure I actually fixed the issue.
=> add bug tests from #608 just to be sure.

addons/gut/test.gd, documentation/docs/Asserts-and-Methods.md, test/unit/test_test.gd
=> Implement `assert_lte` and `assert_gte`

documentation/docs/Double-Strategy.md, documentation/docs/Doubles.md
=> updated double/double-strat pages

.gutconfig.json, CHANGES.md, addons/gut/double_templates/function_template.txt, addons/gut/double_tools.gd, addons/gut/logger.gd, addons/gut/method_maker.gd, addons/gut/stub_params.gd, addons/gut/stubber.gd, addons/gut/test.gd, documentation/docs/Stubbing.md, test/gut_test.gd, test/integration/test_doubler_and_stubber.gd, test/integration/test_test_stubber_doubler.gd, test/resources/doubler_test_objects/double_me.gd, test/unit/test_double_tools.gd, test/unit/test_gut.gd, test/unit/test_stub_params.gd, test/unit/test_stubber.gd, test/unit/test_test.gd
This adds the ability to stub a method on a double to call a specified `Callable`.
=> Add Stub `to_call`

.gutconfig.json, addons/gut/script_parser.gd, test/unit/test_doubler.gd, test/unit/test_script_parser.gd
=> Parsed Native Refcounted Objects are not freed.

addons/gut/input_sender.gd, documentation/docs/Input-Sender.md
=> added class_name to InputSender

addons/gut/gut.gd, test/integration/test_gut_skip_scripts.gd, test/resources/awaiting_post_run_script.gd, test/resources/awaiting_pre_run_script.gd, test/unit/test_gut.gd
=> add await in pre-run script, post-run scrpt, and should_skip_script.

addons/gut/test.gd, test/unit/test_test.gd
=> add default title to assert_not_freed

CHANGES.md, addons/gut/test.gd
=> include parameter list in passing test message

CHANGES.md, addons/gut/awaiter.gd, addons/gut/test.gd, documentation/docs/Awaiting.md, documentation/docs/class_ref/class_guttest.rst, test/unit/test_awaiter.gd, test/unit/test_test_await_methods.gd
Adds `wait_while`.  Implements #630 .
=> I630 wait while

addons/gut/cli/optparse.gd, addons/gut/test.gd, documentation/docs/Awaiting.md, documentation/docs/Memory-Management.md, documentation/docs/Quick-Start.md, documentation/docs/Running-On-Devices.md, documentation/docs/class_ref/class_addons_gut_cli_optparse.rst, documentation/docs/class_ref/class_guttest.rst, documentation/docs/index.rst
Last minute changes to documentation before publishing 9.4.0
=> 9.4.0 documentation changes
