addons/gut/gut.gd
addons/gut/gut_cmdln.gd

This adds some consistency on how the `gut` directory is being referenced and also fixes an exception on Linux.

Fix exception on case sensitive file systems

---

addons/gut/test.gd
test/samples/test_readme_examples.gd
test/unit/test_test.gd

Hey there.
First off, gotta say this is a fantastic utility you're cooking up here. :+1:
Anyway, I usually start new node scripts thinking about what signals and/or editor properties they might need. So I wanted a counterpart to assert_has_signal. Probably some overlap with assert_get_set_methods, but I don't always need getters/setters and I like to have a check that the property itself exists on the object.
assert_has_editor_property(obj, property_name, type)
Asserts that passed object has an exported property named 'property_name' of built-in type 'type'
```GDScript
class ExportClass:
export var some_number = 5
export(PackedScene) var some_scene
var some_variable = 1
func test_assert_has_editor_property():
var obj = ExportClass.new()
gut.p('-- passing --') …
```

assert_has_editor_property

---

addons/gut/gut_cmdln.gd

This allows continuous integration services to detect whether or not the tests
ran through successfully.

Set exit code based on failed tests

---

addons/gut/gut_cmdln.gd

When running gut from command line, it becomes possible to accidentaly
push changes that didn't pass the tests when using continuous integration
if `should_exit` option is not set.
This fixes the described issue by ensuring that the exit code is set regardless
of possible options. It's also not necessary to set exit code to zero because
the program exits with zero by default.

Set exit code on failed tests despite `should_exit` option

---

.gutconfig.json
addons/gut/gut.gd
addons/gut/gut_cmdln.gd
addons/gut/gut_gui.gd
scenes/main.tscn
templates/.gutconfig.json

This fits test runner window to the viewport. The fullscreen mode can be
toggled from the editor, from a command line and be fetched from the gut
configuration file.
Also defined `title_offset` variable to automatically fetch the window's
title bar height that was hardcoded and used for positioning the window.

Add maximize option to command line and the editor

---

addons/gut/doubler.gd

Line 354. Method clear_output_directory creates "var files = []" but seems to never use or return it.

Remove unused variable from clear_output_directory

---

README.md
addons/gut/doubler.gd
addons/gut/stub_params.gd
addons/gut/stubber.gd
test/integration/test_doubler_and_stubber.gd
test/resources/stub_test_objects/to_stub.gd
test/unit/test_stub_params.gd
test/unit/test_stubber.gd
test_doubler_temp_file/double_me__dbl0__.gd

Stubbing enhancements
* adds `to_do_nothing` so that you can suppress warnings about unstubbed methods.
* adds `to_call_super` so that the method will call the super method instead of being stubbed out.
* modifies `to_return` so that any call to it will negate a call to `to_call_super`.  This is so we can implement partial stubs later on.

V6.7.1 issue98

---

addons/gut/signal_watcher.gd

In Godot 3.2.2-beta I've been getting this error (while `yield_for` test):
```
* test_state
Testing: test_body_state
/# Yielding to signal "completed" or for 5 seconds #/ 
Debugger Break, Reason: 'Invalid get index '[Deleted Object]' (on base: 'Dictionary').'
*Frame 0 - res://addons/gut/signal_watcher.gd:152 in function 'clear'
```
I'm not sure what was merged to 3.2.2 that emits this error, yet I've reordered the object validity check and tests pass now. I wonder whether that's a symptom or a solution.
This might be quite related to godotengine/godot#38322, so this might have just revealed a hidden bug in GUT.
Also, consider switching to [`is_instance_valid`](https://docs.godotengine.org/en/3.2/classes/class_@gdscript.html#class-gdscript-method-is-instance-valid) method, works reliably …

Check for object validity earlier in signal watcher

---

addons/gut/orphan_counter.gd

no crash when assert_no_new_orphans() is run before any test

---

addons/gut/gut.gd
addons/gut/gut_cmdln.gd

After creating a GitHub Action for running GUT tests on GitHub CI I've noticed that the script does exit with error code 0 if the configuration is wrong, or the given path does not exist. And so this causes the CI passing, even tho no test is executed.
This PR address these situations by returning the -1 error code and so making CI fail.

exits with 1 if configuration or path is wrong

---

.gutconfig.json
CHANGES.md
addons/gut/gut.gd
test/resources/parsing_and_loading_samples/test_with_parameters.gd
test/unit/test_gut.gd

Fixes 202.   `before_each` and `after_each` are now called before and after each parameterized test.

Fixes #202 

---

CHANGES.md
addons/gut/strutils.gd

Special case when determining object filename of a GDNative script.  
Calling inst2dict fails for GDNative scripts, but we can directly obtain the resource path from the script instance.
Fixes #211

File paths for GDNative

---

test/integration/test_test_stubber_doubler.gd

Was looking at the wiki, and found this same typo on the code sample in the [Quick Start for Partial Doubles](https://github.com/bitwes/Gut/wiki/Quick-Start#partial-doubles) on the first line `var double_bar = parital_double('res://bar.tscn').instance() `
Couldn't find a way to do a PR on the wiki, so searched the code and found this one there as well.

minor: Fixing typo in test name

---

addons/gut/input_sender.gd
test/unit/test_input_sender.gd

Generate a warning when a key_down, action_down, mouse_button_down is sent for a 2nd time without being released.  When using `Input` as a receiver it will not process multiple *_down events unless they have been released between.  With this warning it is now trivial to debug those tests.

Warn on down without release

---

.gut_editor_config.json
BigFont.tres
BigFontTheme.tres
addons/gut/GutScene.tscn
addons/gut/gui/GutSceneTheme.tres

Replicated the issue described in #283 by setting a large default theme.  By adding a theme to `GutScene.tscn` that had a default font.  This stopped the project font from being applied to the Gut Scene.
fixes #283

Added theme to GutScene that has a default font

---

CHANGES.md
addons/gut/GutScene.tscn
addons/gut/double_templates/script_template.txt
addons/gut/doubler.gd
addons/gut/gui/GutSceneTheme.tres
addons/gut/method_maker.gd
addons/gut/strutils.gd
addons/gut/stub_params.gd
addons/gut/stubber.gd
addons/gut/test.gd
addons/gut/utils.gd
test/integration/test_doubler_and_spy.gd
test/integration/test_doubler_and_stubber.gd
test/integration/test_gut_and_stubber.gd
test/integration/test_test_stubber_doubler.gd
test/resources/stub_test_objects/has_stub_metadata.gd
test/resources/stub_test_objects/to_stub.gd
test/unit/test_doubler.gd
test/unit/test_strutils.gd
test/unit/test_stub_params.gd
test/unit/test_stubber.gd
test/unit/test_test.gd
test/unit/test_utils.gd

Create doubles and partial doubles of Godot Singletons such as `Input`, `OS`, `JavaScript`.  Any call that results in calling the super method will punch through to the global singleton instance.
```
func test_foo():
var player = Fighter.new()
var dbl_input = double_singleton('Input')
player.local_input_ref = dbl_input
stub(dbl_input, 'is_action_just_pressed').to_return(true).when_passed('jump')
```
```
func test_bar():
var dbl_os = partial_double_singleton('OS')
stub(dbl_os, 'name').to_return('iOS')
var thing = Foo.new()
thing.local_os_ref = dbl_os
```

Double and partial double singletons

---

.gutconfig.json
CHANGES.md
addons/gut/double_templates/init_template.txt
addons/gut/double_templates/script_template.txt
addons/gut/doubler.gd
addons/gut/method_maker.gd
addons/gut/stub_params.gd
addons/gut/stubber.gd
test/integration/test_doubler_and_spy.gd
test/integration/test_doubler_and_stubber.gd
test/integration/test_test_stubber_doubler.gd
test/resources/stub_test_objects/init_parameters.gd
test/unit/test_doubler.gd

This PR adds:
* The ability to pass parameters to `new` when instancing doubles and partial doubles.
* The ability to stub default parameter values for `_init`.
* The ability to spy on parameters passed to `_init`.
See CHANGES.md for examples.

I354 init parameters

---

CHANGES.md
addons/gut/method_maker.gd
test/unit/test_bugs/test_i368_WebSocketClient_double.gd
test/unit/test_method_maker.gd

Adds `PoolStringArray` as a supported default value type.  Also fixes a bug that prevented an error message from appearing when an unsupported datatype was encountered.

Fix #368.  Add PoolStringArray as a supported default.

---

CHANGES.md
addons/gut/UserFileViewer.tscn
addons/gut/input_sender.gd
addons/gut/test.gd
addons/gut/utils.gd
scratch/test_35_input_sender.gd
test/unit/test_input_sender.gd
test/unit/test_orphan_counter.gd
test/unit/test_utils.gd

Adds `auto_flush_input` to `InputSender`.  This will make the `InputSender` behave as if `Input.use_accumulate_input` was disabled (enabled by default in Godot 3.5).  This gives you the option to set this on `InputSender` without having to worry about setting and resetting `use_accumulate_input` in your tests (at the cost of having to set it on every `InputSender` you create).
When `use_accumulate_input` is enabled and `auto_flush_input` is disabled (it is by default), then any input sent through `Input` via `InputSender` or anywhere else will not be processed until the end of a frame.

I387 accumulate input

---

addons/gut/gui/gut_config_gui.gd
addons/gut/gut.gd
addons/gut/gut_cmdln.gd
addons/gut/plugin_control.gd
scenes/TestPrint.tscn
test/resources/parsing_and_loading_samples/test_with_specific_suffix.gd
test/unit/test_gut_directory.gd

Fixes #375 
Adds a new control field to `gut_config_gui.gd` for `Script Suffix` and propagates its value to the workspace config file.
Reports an error if the user specifies a `suffix` which does not end in `.gd`.
Allows `file_prefix` to be empty (i.e. `''`).
- The previous error message says it must not be empty or GUT cannot find any scripts. However, in reality an empty prefix will match all files, which is actually what the user probably wants.
Both fields retain their default values of `test_` and `.gd` respectively.
Adds a new test and test sample file to express the suffix matching behavior. 
There do not seem to be any tests covering the `gut_config_gui` it self, though I'm not sure how to test such a thing.
Please let me know if you see a gap in coverage.
----
Wiki Text Update: …

Allow specifying an empty FilePrefix and a FileSuffix from in-editor Plugin Controller

---

addons/gut/gui/OutputText.gd
addons/gut/gui/RunResults.gd

Fixes a few errors relating to 4.0 name changes that appear after enabling the plugin within a 4.0 project.
I noticed there are two 4.0 related branches.  Not sure if this is the main one, but seeing as it was updated recently I decided to use it as a base.

4.0 Name Change Errors

---

addons/gut/gui/GutBottomPanel.gd
addons/gut/gui/OutputText.gd

- Addresses a part of #384 regarding the conversion of `button.pressed` to `button.button_pressed` in 4.0 for `GutBottomPanel` and `OutputText`
- Fixes a  `_on_results_bar_draw` binding in `GutBottomPanel` according to #383

4.0 Button Pressed in GutBottomPanel & OutputText

---

addons/gut/gui/gut_config_gui.gd

An infinite loop occurs while attempting to initialize `gut_config_gui` due to `set_text` calling into itself via `text = t`, resulting in an editor crash while opening a project with the plugin enabled.  In case it's relevant, I'm running the editor and plugin on Windows 10.
Interestingly, I received no error messages (such as an out of memory error / exception) from the engine while trying to nail down the source, even when running the editor in verbose mode.  
I removed the `set_text` function in `DirectoryCtrl`, migrating the logic into the setter. 
~~#### Extras~~
~~I changed the `add_child` calls to `call_deferred` in `DirectoryCtrl::_ready` as I believe this is the preferred method for adding children in `_ready`.~~

4.0 DirectoryCtrl::set_text Infinite Loop Fix

---

addons/gut/gui/ShortcutButton.gd

Fixes up `ShortcutButton` to display and set shortcuts with Godot 4.
`ShortcutButton::to_s` was reduced to use the new engine functions in order to grab the human-readable display.  This display uses capitalization which is a slight change from the existing display.   Please let me know if you'd like it to be uncapitalized to match the previous version.
Additionally, I added `command_pressed` from `InputEventWithModifiers` in the modifier check functions.  Perhaps it isn't required.  Let me know if you'd like it removed.

4.0 Shortcuts

---

addons/gut/gui/RunResults.gd
addons/gut/gui/script_text_editor_controls.gd

Applies some name & class changes for 4.0 so clicking on the `RunResult` lines opens the proper file at the specified line (when applicable and if used with #404).

4.0 Run Result Line Select Fixes

---

addons/gut/strutils.gd

Fixes the name change `inst2dict` to `inst_to_dict` in `strutils` for Godot 4, and restores the commented out logic

Godot 4 Inst to Dict

---

addons/gut/gut.gd
addons/gut/test.gd
test/unit/test_gut.gd

Right now, Gut's `simulate` function will call `_physics_process` and `_process` on a `Node` [as long as the methods are overridden](https://github.com/bitwes/Gut/blob/fe292bcdcf9baca6022944ecdb0f973083ff3ed4/addons/gut/gut.gd#L1349-L1352). However, it's possible for a `Node` to disable its `_physics_process` method using `set_physics_process(false)` and `_process` method using `set_process(false)`. The `simulate` function should respect when a `Node` toggles the status of its  `_physics_process` and `_process` methods.
Regarding the implementation here, I think it would be correct to simply replace the `if(obj.has_method("_process")):` check with `if (obj.is_in_group("idle_process")):`. This is because these groups are [set by Godot](https://docs.godotengine.org/en/stable/classes/class_no …

Allow simulate to check whether a Node has disabled its process methods

---

addons/gut/gut.gd

Fixes yielding (awaiting) for signals in Gut in Godot 4.
For testing, I used a simple `GutTest` which emits a button press (below);
```
func test_pressed():
var button = autofree(SomeButton.new())
add_child(button)
await yield_to(button, "pressed", 1).timeout
button.emit_signal("pressed")
assert_signal_emitted(button, "pressed")
```

Godot 4 Yield To Fix

---

addons/gut/doubler.gd
addons/gut/gui/script_text_editor_controls.gd
addons/gut/gut.gd
addons/gut/gut_cmdln.gd
addons/gut/hook_script.gd
addons/gut/spy.gd
addons/gut/stub_params.gd
addons/gut/stubber.gd
addons/gut/test.gd
addons/gut/utils.gd
scratch/find_bad_methods.gd
scratch/make_class_from_string.gd
scripts/main.gd
test/integration/test_doubler_and_stubber.gd
test/integration/test_everything_together.gd
test/integration/test_gut_and_spy.gd
test/integration/test_gut_and_stubber.gd
test/resources/parsing_and_loading_samples/test_samples.gd
test/resources/parsing_and_loading_samples/test_samples2.gd
test/resources/parsing_and_loading_samples/test_samples3.gd
test/samples/test_readme_examples.gd
test/samples/test_sample_one.gd
test/unit/test_doubler.gd
test/unit/test_stubber.gd
tests_4_0/test_gut.gd

It looks like at some point there was a bulk find/replace of instance -> instantiate, which made some comments incorrect.

Fix "instantiate" being used as a noun or adjective

---

GODOT_4_README.md
Godot_4_latest_run.md
addons/gut/comparator.gd
addons/gut/diff_tool.gd
addons/gut/summary.gd
addons/gut/test.gd
addons/gut/utils.gd
test/gut_test.gd
test/integration/test_test_stubber_doubler.gd
test/samples/test_readme_examples.gd
test/unit/test_comparator.gd
test/unit/test_diff_formatter.gd
test/unit/test_diff_tool.gd
test/unit/test_test.gd

* Compares dictionaries and arrays by value using `==` by default.  This matches Godot 4's behavior.
* Removed shallow compare methods and asserts.
* Added `assert_same` and `assert_not_same` which can be used to compare dictionaries/arrays by reference.

Godot 4 fix array dictionary compare

---

addons/gut/gut.gd
test/unit/test_gut_yielding.gd

If the signal emits the value 'false' as the first argument this will assume that it's the bound 'false' value which signifies a timeout.. This is because bound arguments appear at the end of the callback parameter list, not a the beginning.
Instead of using true/false, this change binds a sentinel. We can definitively know whether the callback came from the bound signal or a timeout.
See also https://github.com/bitwes/Gut/issues/327

Fix issue where yield_to can return too early

---

addons/gut/gut.gd

This removes a deprecated call which was remarked in the test output.
```
[DEPRECATED]:  gut.clear_text
...
(rest of output omitted for brevity)
...
Warnings/Errors:
* 1 Deprecated calls.
```
In my own running from GUI and command line, I did not notice any negative effects from removing this call,
but if you are aware of any, then please reject this PR.
Resolves #468

Remove call to deprecated clear_text()

---

addons/gut/gut_cmdln.gd

`super.gutconfig.json` → `.gutconfig.json` in some feedbacks

Fix possible overzealous 3to4 conversion

---

addons/gut/gut_cmdln.gd
wiki/Hooks.md

With GUT 9, gut_cmdln exits with exit code 0 even if tests failed.
This should fix this, at least if `-gexit` (`should_exit`) is set.
When manually exiting GUT (`-gexit` not set or with `-gexit_on_success`), the exit code will still be 0.
However, I don't think it's that important to have a exit code != 0, when manually running GUT,
since the exit code is mainly relevant for CI pipelines, which probably always run with `-gexit`.
Note: There is one more uncommented usage of `OS.exit_code` [here](https://github.com/bitwes/Gut/blob/godot_4/addons/gut/gut.gd#L1145).
I'm not quite sure how to fix it. Maybe just exit immediately?

fix exit code when should_exit is set

---

wiki/Command-Line.md

I've added double quotes around `$PWD` so that the commands work when the directory contains spaces.
I've also added bash syntax type for the markdown.

Commands when $PWD contains spaces

---

CHANGES.md
addons/gut/test_collector.gd
test/resources/parsing_and_loading_samples/test_does_not_extend_guttest.gd
test/unit/test_doubler.gd
test/unit/test_gut.gd
test/unit/test_test_collector.gd

GUT will now print a warning and ignore scripts that do not extend `GutTest`.

I485 ignore non guttest scripts

---

addons/gut/gut_to_move.gd
addons/gut/test.gd
test/unit/test_gut.gd

PR #409 has not been merged into the `godot_4` branch, so this PR applies the same changes to that branch. A few minor changes were made to the test code (in `test/unit/test_gut.gd`):
1. `assert_pass` no longer exists on `TestSimulate`, so I removed those assertions. If you'd prefer, I can update `TestSimulate` to manage assertion counts (like how `TestEverythingElse` does it) and then re-add the `assert_pass` calls.
2. I noticed that the local variable name `is_processing` in `test_simulate_calls_process_if_object_is_processing_and_check_is_true` shadows a built-in method, so I updated a number of local variable names in the tests to fix this issue while keeping naming consistent.
3. I now manually construct a few object arrays instead of using for loops (e.g. in …

chore(simulate): apply PR #409 to godot_4 branch

---

addons/gut/stubber.gd

If the user sets the `debug/gdscript/warnings/untyped_declaration` property in their project to `Error`, tests will fail to run even if `Exclude Addons` is checked. This is probably because this particular bit of code is created dynamically from a string, so the editor doesn't realize that it's actually from an addon.

Fix untyped declaration error in Godot 4.2

---

documentation/docs/Quick-Start.md

Hi,
I did not see this requirement listed anywhere and it was the only way I could get GUT to find my tests I named my test file class_name_test.gd).
Is there another way?

Add note about file name requirement.

---

CHANGES.md
addons/gut/test.gd
test/unit/test_test.gd

Extra precision added for float, vector2, vector3 in assert_almost_eq, assert_almost_ne, assert_between, assert_not_between.

i523 Add precision for float, vector2, vector3

---

CHANGES.md
addons/gut/gui/gut_config_gui.gd
addons/gut/gut.gd
test/unit/test_gut_yielding.gd

Yield timer is now stopped to be extra sure that yield time does not leak between tests.  `output_font_name` and `output_font_size` are now saved in the Gut Panel.  Yea, there's two bugs in this one PR.  I got lazy.  Settle down.

fixed #450 and #547

---

addons/gut/input_sender.gd
test/unit/test_input_sender.gd

InputSender will now emit the `gui_input` signal. I have verified the natural order with a [minimal project](https://github.com/bitwes/Gut/files/13818986/InputOrderTest.zip), wich gave me this order:
```
_input function
gui_input signa
_gui_input function
_unhandled_input function
```
So i basically just inserted the artificial signal emission between `_input()` and `_gui_input()` artificial calls.
Bonus: I turned Strings into StringNames, because it's the desired parameter's type of `has_method()` and `has_signal()`.

Fix InputSender not emiting the `gui_input` signal

---

CHANGES.md
addons/gut/gui/gut_config_gui.gd
addons/gut/gui/panel_controls.gd
addons/gut/gut_config.gd
scenes/TestPanelControls.gd

Add a CheckButton to each directory in the Settings Subpanel.  When switched off, the directory will not be included when running tests.  This makes it easier to run a subset of tests through the editor.

Disable a directory when running tests through editor

---

CHANGES.md
addons/gut/gut_cmdln.gd
addons/gut/method_maker.gd
addons/gut/utils.gd
test/unit/test_nothing.gd

Fixes #542.  `GutUtils` is now an `Object` and is freed at the end of the run.  Thanks to @ngburke  for the idea.

implement GutUtils as Object fix

---

.gutconfig.json
CHANGES.md
addons/gut/doubler.gd
addons/gut/utils.gd
test/resources/implicit_initializer_class.gd
test/resources/uses_implicit_initializer.gd
test/unit/test_bugs/test_i570_implicit_initializer.gd

All doubles now have the `resource_path` set to a unique value which appears to work around #570.

I570 doubling and static typed things

---

CHANGES.md
addons/gut/gut_cmdln.gd
addons/gut/gut_vscode_debugger.gd

Down an dirty way to enable the console printer when running debugger via vscode.

add debugger version of gut_cmdln

---

addons/gut/gut_config.gd

GUT will throw errors if `exclude_addons` option is disabled, e.g. due to overriding native methods.
When working on addons it is usually desired to disable `exclude_addons` in order to get proper code diagnostics.
This however makes it tedious to run GUT because the option has to be manually disabled before running tests and manually enabled again afterwards to get diagnostics.
To workaround this issue, this commit automatically enables the `exclude_addons` option when running tests, so regardless of the project settings in the editor, GUT will always run as intended.

Automatically enable `exclude_addons` option when running tests

---

addons/gut/collected_test.gd
addons/gut/gut.gd
addons/gut/junit_xml_export.gd
addons/gut/result_exporter.gd
test/resources/exporter_test_files/test_time_taken.gd
test/unit/test_junit_xml_export.gd
test/unit/test_result_exporter.gd

I made the changes in a fork to better work with this GitHub test reporter: https://github.com/dorny/test-reporter
* Removed "res://" from reported file paths. This enables you to click on a report in the above tool and take you to the change in Github that caused the failure.
* Reporting Time taken for each test. This fills in the time column in the above tool instead of reporting "null".
* There was a formatting change in collected_test.gd where it was using spaces instead of tabs.  
Output from the test-reporter tool with the changes:
I'm more than happy to split into different PRs or remove bits that aren't interesting to keep (and of course understand if it's not something wanted at all 😄).

Output Time in exported results. Clean res:// from path. 

---

addons/gut/gut.gd
addons/gut/test.gd

I enabled various warnings in `debug/gdscript` related to enforcing static typing, e.g. `unsafe_property_access` or `unsafe_method_access`.
I also treat some of them as errors.
I've just wrote a unit test and immediately ran into errors because Gut doesn't seem to make much use of static typing.
This patch gives the `gut` object a `class_name` and adds an explicit return type to the `get_elapsed_time` function.
I'm not sure if `GutContext` is a sensible name for this class, I'm open for suggestions.
This patch just contains fixes for the parts that immediately caused errors in my workflow.
There might be more PRs to come in the future if I run into trouble again :)

Improve static typing support

---

CHANGES.md
addons/gut/input_sender.gd
test/unit/test_input_sender.gd

Mouse motion button mask

---

.gutconfig.json
CHANGES.md
GODOT_4_README.md
addons/gut/collected_script.gd
addons/gut/collected_test.gd
addons/gut/gut.gd
addons/gut/test.gd
addons/gut/test_collector.gd
documentation/docs/Asserts-and-Methods.md
documentation/docs/New-For-Godot-4.md
test/gut_test.gd
test/integration/test_gut_skip_scripts.gd
test/integration/test_more_input_ideas.gd
test/unit/test_test.gd
test/unit/test_test_collector.gd

Added the virtual method `should_skip_script` to `GutTest`.  If you impelement this method and return `true` or a `String`, then GUT will skip the script.  Skipped scripts are marked as "risky" in the final counts.  This can be useful when skipping scripts that should not be run under certiain circumstances such as:
* You are porting tests from 3.x to 4.x and you don't want to comment everything out.
* Skipping tests that should not be run when in `headless` mode.
``` gdscript
func should_skip_script():
if DisplayServer.get_name() == "headless":
return "Skip Input tests when running headless"
```
* If you have tests that would normally cause the debugger to break on an error, you can skip the script if the debugger is enabled so that the run is not interrupted.
``` gdscript
func …
```

I598 skipping scripts

---

addons/gut/awaiter.gd
addons/gut/doubler.gd
addons/gut/gut.gd
addons/gut/test.gd
documentation/docs/Asserts-and-Methods.md
test/unit/test_awaiter.gd
test/unit/test_test_await_methods.gd

First step for issue: https://github.com/bitwes/Gut/issues/585
Replaces https://github.com/bitwes/Gut/pull/577. Closing it.

assert_eventually(predicate_function, ...)

---

addons/gut/input_sender.gd
test/unit/test_bugs/test_i578.gd
test/unit/test_input_sender.gd

The hope here is to resolve #578
I haven't done any cleanup as suggested by @bitwes over in the issue thread. But the fix he suggested works just fine, and this PR is evidence of that.

WIP: Bugfix/i578

---

CHANGES.md
addons/gut/stub_params.gd
addons/gut/test.gd
documentation/docs/Quick-Start.md
documentation/docs/Stubbing.md
test/integration/test_stub_in_before_each.gd
test/integration/test_test_stubber_doubler.gd
test/unit/test_stub_params.gd

You can now use callables to `stub`.  Binding arguments adds `when_passed` to the stub.  Less strings, less typing!
```gdscript
var dbl = double(MyScript)
stub(dbl.some_method).to_return(111)
stub(dbl.some_method.bind("a")).to_return(999)
```

Stub with callables

---

documentation/docs/Input-Factory.md

I fixed **[MD011](https://github.com/DavidAnson/markdownlint/blob/main/doc/md011.md)** *no-reversed-links* - Reversed link syntax of **Mocking-Input**.

fix: Mocking-Input link

---

addons/gut/gui/GutRunner.gd
addons/gut/test.gd

I was hit with the "configrued" error message, so I decided to go and review the other messages. I found three small things to fix.

Fixed typos in error messages.

---

addons/gut/fonts/AnonymousPro-Bold.ttf.import
addons/gut/fonts/AnonymousPro-BoldItalic.ttf.import
addons/gut/fonts/AnonymousPro-Italic.ttf.import
addons/gut/fonts/AnonymousPro-Regular.ttf.import
addons/gut/fonts/CourierPrime-Bold.ttf.import
addons/gut/fonts/CourierPrime-BoldItalic.ttf.import
addons/gut/fonts/CourierPrime-Italic.ttf.import
addons/gut/fonts/CourierPrime-Regular.ttf.import
addons/gut/fonts/LobsterTwo-Bold.ttf.import
addons/gut/fonts/LobsterTwo-BoldItalic.ttf.import
addons/gut/fonts/LobsterTwo-Italic.ttf.import
addons/gut/fonts/LobsterTwo-Regular.ttf.import

The Godot editor 4.3 adds this by default.
https://github.com/bitwes/Gut/issues/673

Font import files: Add disable_embedded_bitmaps

---

addons/gut/gui/editor_globals.gd
addons/gut/gut_config.gd
addons/gut/logger.gd
addons/gut/utils.gd
test/unit/test_gut_config.gd

Changed the warning to only appear when a non-default config path is opened.  Fixes #592.

Remove editor config file warning

---

GODOT_4_README.md
README.md
addons/gut/input_factory.gd
addons/gut/test.gd
documentation/README.md
documentation/docs/Contributing.md
documentation/docs/Doubles.md
documentation/docs/Memory-Management.md
documentation/docs/New-For-Godot-4.md
documentation/docs/class_ref/class_gutinputfactory.rst
documentation/docs/class_ref/class_guttest.rst
documentation/generate_rst.sh

Just a few typos here and there, and one clarification of a sentence I thought was a little confusing to read.
I also added a small bit to the `generate_rst.sh` file so that I could build it on my linux machine (otherwise it would use the mac version of a command that I don't have here).

Fix docs typo

---

CHANGES.md
addons/gut/doubler.gd
test/resources/simple_scene.gd
test/resources/simple_scene.tscn
test/unit/test_bugs/test_issue_SOTB.gd

Fixes #666 
Originally doubled scenes were created with super cool and witty programming.  Godot is getting better (worse?) at not calling overridden methods and would not call my super cool and witty code when a variable had a type of `PackedScene`.  This is probably because it knew enough to not call the method in the script since it had a type.  The new approach for creating a doubled scene is a lot more straight forward and gets around the issues the witty code was causing.

fixed issue

---

.gutconfig.json
CHANGES.md
GODOT_4_README.md
addons/gut/awaiter.gd
addons/gut/test.gd
documentation/docs/Awaiting.md
documentation/docs/New-For-Godot-4.md
documentation/docs/Quick-Start.md
documentation/docs/class_ref/class_guttest.rst
test/integration/test_everything_together.gd
test/output_tests/test_print.gd
test/unit/test_awaiter.gd
test/unit/test_bugs/test_i288_wait_times.gd
test/unit/test_bugs/test_i578.gd
test/unit/test_gut.gd
test/unit/test_gut_config_gui.gd
test/unit/test_gut_runner.gd
test/unit/test_illustrate_input_and_button_event_issue.gd
test/unit/test_input_sender.gd
test/unit/test_test.gd
test/unit/test_test_await_methods.gd

Implements #675
* deprecates `GutTest.wait_frames`
* adds `GutTest.wait_physics_frames` to replace `wait_frames`
* adds `GutTest.wait_process_frames`

Refactor wait methods

---

addons/gut/junit_xml_export.gd

Ran into an issue with parsing the XML of the exported test results when the error message has null in it as in Godot `str(null)` is `<null>`:
```
<failure message="failed">params[10] Expected [<null>] to be anything but NULL:  [message]
at line -1</failure>
```
I was able to solve the issue locally with this change, but not sure if there's another route you'd prefer (eg escaping certain characters).

Wrap skipped and failure messages in CDATA

---

test/unit/test_optparse.gd

In test_optparse.TestValueDictionary.test_values_contains_positional_arguments_default_value, `op.parse()` is called to see if a positional argument would be filled with its default value when no arguments are given. However, `op.parse()` is called with no arguments instead of an empty list, which actually passes it arguments passed to the godot process. 
Because of this, running the test with `godot -d -s addons/gut/gut_cmdln.gd -gtest test/unit/test_optparse.gd` (with no .gutconfig.json file) fails with `[Failed]:  ["test/unit/test_optparse.gd"] expected to equal ["asdf"]:`.
By passing it an empty list we ensure it tries to parse no arguments, and the test no longer fails when run with the above command.

fix failing test_optparse.TestValuesDictionary test

---

addons/gut/input_sender.gd
test/unit/test_input_sender.gd

It has bothered me that I haven't updated this to match the naming conventions of the various `wait_*` methods in `GutTest`, so I made them.

add hold_frams and hold_seconds to input sender

---

documentation/docs/Awaiting.md

Fix typo in the Awaiting documentation

---

addons/gut/inner_class_registry.gd
addons/gut/script_parser.gd
test/resources/parsing_and_loading_samples/cyclic_ref_class_a.gd
test/resources/parsing_and_loading_samples/cyclic_ref_class_a.gd.uid
test/resources/parsing_and_loading_samples/cyclic_ref_class_b.gd
test/resources/parsing_and_loading_samples/cyclic_ref_class_b.gd.uid
test/unit/test_inner_class_registry.gd

If you have the following:
```gdscript
const B := preload("res://b.gd")
const A := preload("res://a.gd")
```
Calling `register_inner_classes` on `A` results in a stack overflow.

fix: register_inner_classes can handle cyclic dependencies
